# Generated by Django 5.2.8 on 2025-11-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0004_seed_presses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(help_text="Markdown 형식으로 내용을 작성하세요."),
        ),
    ]
