# Generated by Django 5.2.8 on 2025-11-17 11:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0005_alter_article_content"),
        ("Main", "0005_article_author"),
    ]

    operations = []
